### ISSUE TITLE
能否提供一些例子？

### ISSUE THREAD

**Issue by Chenqijia1234** [lrsgzs/cat#1]
关于cat lang，我们大家需要一些示例和文档，谢谢！

**Comment by lrsgzs** [comment]
哦，回头有空了就会做。
我在b站有个视频，就是关于cat lang的
【cat语言发布-哔哩哔哩】 https://b23.tv/9tEkvKJ

来自 刘F硕 的iPad <大号>

**Comment by lrsgzs** [comment]
#5 更新日志
