### ISSUE TITLE
恭喜

### ISSUE THREAD

**Issue by ikun-lychee** [lrsgzs/cat#2]
喜提作品上C站首页
![image](https://user-images.githubusercontent.com/110650497/216301493-26466895-09d1-4a2f-9a27-ac51a0ce4652.png)

**Comment by lrsgzs** [comment]
过奖

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

**Comment by ikun-lychee** [comment]
🌚
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>《via email》《通 过 邮 件 发 送》
怎么搞？

**Comment by lrsgzs** [comment]
正常。我懒着打开浏览器看了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

























《via email》《通 过 邮 件 发 送》
怎么搞？

―

**Comment by Chenqijia1234** [comment]
就像这样？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月2日(周四) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lrsgzs/cat] 恭喜 (Issue #2)




 
🌚
 





























《via email》《通 过 邮 件 发 送》
 怎么搞？

**Comment by lrsgzs** [comment]
Az，我会手动在邮件编辑页面删除不必要的东西

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送
























《via email》《通 过 邮 件 发 送》
怎么搞？

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

―

**Comment by ikun-lychee** [comment]
md
![image](https://user-images.githubusercontent.com/110650497/216304519-6169e277-a62e-4748-b6f3-011e1fc11d82.png)


<br/><br/><br/><br/><br/><br/>不是那我的

你干嘛哈嗨呦你好烦+ikun-lychee@users.noreply.github.com

的密码是什么？

**Comment by lrsgzs** [comment]
不知道

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月2日 18:52
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [lrsgzs/cat] 恭喜 (Issue #2)


md
[image]<https://user-images.githubusercontent.com/110650497/216304519-6169e277-a62e-4748-b6f3-011e1fc11d82.png>






不是那我的

***@***.******@***.***>

的密码是什么？

―

**Comment by ikun-lychee** [comment]
那我试？
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年2月2日 18:42
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [lrsgzs/cat] 恭喜 (Issue #2)
        
      
    
  
  

就像这样？















---原始邮件---



发件人: ***@***.***&gt;



发送时间: 2023年2月2日(周四) 晚上6:40



收件人: ***@***.***&gt;;



抄送: ***@***.***&gt;;



主题: Re: [lrsgzs/cat] 恭喜 (Issue #2)



















 



🌚



 























































































































《via email》《通 过 邮 件 发 送》



 怎么搞？

**Comment by lrsgzs** [comment]
？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

**Comment by ikun-lychee** [comment]
🌚太棒了

**Comment by ikun-lychee** [comment]
邮箱果然是个好东西

**Comment by ikun-lychee** [comment]
顺便问一下，你用的是pycharm还是vscode？

（所有JetBrains软件都强大）

**Comment by Chenqijia1234** [comment]
> 喜提作品上C站首页 ![image](https://user-images.githubusercontent.com/110650497/216301493-26466895-09d1-4a2f-9a27-ac51a0ce4652.png)

《内存已超标》

**Comment by lrsgzs** [comment]
都用

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

**Comment by ikun-lychee** [comment]
☹️☹️☹️☹️☹️☹️☹️☹️☹️☹️☹️☹️😅😅😅😅☹️☹️☹️☹️☹️☹️☹️☹️☹️☹️☹️☹️



发自我的iPad


------------------ 原始邮件 ------------------
发件人: lrs ***@***.***&gt;
发送时间: 2023年2月2日 19:48
收件人: lrsgzs/cat ***@***.***&gt;
抄送: 张杰 ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[lrsgzs/cat] 恭喜 (Issue #2)





 都用 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;发送

**Comment by ikun-lychee** [comment]
> > 喜提作品上C站首页 ![image](https://user-images.githubusercontent.com/110650497/216301493-26466895-09d1-4a2f-9a27-ac51a0ce4652.png)
> 
> 《内存已超标》

腻赣嫲铪亥悠

**Comment by ikun-lychee** [comment]
再次喜提出现出现分支（最后一次）

![image](https://user-images.githubusercontent.com/110650497/216871613-fd7a5497-1c5e-4790-bbbb-b11de8d476d3.png)

**Comment by lrsgzs** [comment]
#5 更新日志
