### ISSUE TITLE
嗨嗨嗨我又来了🌚

### ISSUE THREAD

**Issue by ikun-lychee** [lrsgzs/cat#3]
那个能不能添加第三方模块支持？

**Comment by Chenqijia1234** [comment]
不能理解你的意思。如果你想要支持在cat中运行Python命令，只需要支持一个eval函数即可

**Comment by ikun-lychee** [comment]
呃呃呃想起来了，
🌚《用Python开发》






------------------ 原始邮件 ------------------
发件人: ChenQJ ***@***.***&gt;
发送时间: 2023年2月10日 19:37
收件人: lrsgzs/cat ***@***.***&gt;
抄送: 张杰 ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[lrsgzs/cat] 嗨嗨嗨我又来了�� (Issue #3)





 
不能理解你的意思。如果你想要支持在cat中运行Python命令，只需要支持一个eval函数即可

**Comment by ikun-lychee** [comment]
> 呃呃呃想起来了， 🌚《用Python开发》
> […](#)

《用Python开发的Cat语言》🌚

**Comment by lrsgzs** [comment]
#5 更新日志
