### ISSUE TITLE
RDP站长路过

### ISSUE THREAD

**Issue by thepiationesl** [lrsgzs/cat#4]
哇去，这个cat居然可以不用管理员在WindowsServer上面运行，厉害，如果能出个HELP就好了（本人没看完所有以及只会HTML和少量的PHP，看到了请给个链接，谢谢）
![6](https://user-images.githubusercontent.com/125710207/219824606-a3569ec5-7cf3-4f41-a2bb-b5d7ca086ed2.PNG)

**Comment by Chenqijia1234** [comment]
帮助视频可见issue#1
本项目用Python开发，理论上可以在很多平台上运行！

**Comment by esl10** [comment]
我还是喜欢图文教程,因为我是远程桌面服务器RDP你应该知道非常卡
别问我为什么不用本地打开，问就是b站被我爸拿路由器屏蔽了(baned)

**Comment by Chenqijia1234** [comment]
开流量？🐶
图文教程目前没有

**Comment by Chenqijia1234** [comment]
cat启动后会提示你输入cat源码文件名

**Comment by thepiationesl** [comment]
兼容FreeBSD吗？(FreeBSD13.0)
我手上目前也有个debian，只不过他是这样的：
Linux ecs04022 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Apr 14 21:42:49 2023 from 223.107.193.14
root@ecs04022:~#

**Comment by thepiationesl** [comment]
[e12@s1]:<~/gs/cat>$ python3.8 main.py
File Name > configs.py
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    file = open(sys.argv[1], "r", encoding="utf-8")
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    codes = json.load(file)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
[e12@s1]:<~/gs/cat>$

emm...这是什么问题啊

**Comment by thepiationesl** [comment]
[e12@s1]:<~/gs/cat>$ python3.8 main.py
File Name > configs.py
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    file = open(sys.argv[1], "r", encoding="utf-8")
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    codes = json.load(file)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)
[e12@s1]:<~/gs/cat>$

emm...这是什么问题啊

**Comment by thepiationesl** [comment]
我写了针对新手的教程，Bing搜索thepiationesl cat最上面的那一个或者http://esoela.ddo.jp/post/lrsgzs-cat-tuijian.html，侵权请联系删除，谢谢！

**Comment by lrsgzs** [comment]
configs.py是配置文件

**Comment by thepiationesl** [comment]
大佬，还更新吗，我手上目前有Server2016/2019/vNext的机器，而且我会开VMware/VirtualBox/Hyper-V和QEMU虚拟机，这边Ubuntu也有几台，我这边所有Server都测过去了，都能用，如果您需要的话我可以给您提供一下我的测试截图。目前我可以根据演示来完成简单的事情。

**Comment by lrsgzs** [comment]
目前计划更新库的支持，添加内置库

**Comment by lrsgzs** [comment]
#5 更新日志
